# Generated by Django 3.2.4 on 2021-06-24 21:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.CharField(max_length=50)),
                ('humdit', models.CharField(max_length=50)),
                ('waterTemp', models.CharField(max_length=50)),
                ('temp', models.CharField(max_length=50)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 24, 21, 31, 52, 371779, tzinfo=utc))),
            ],
        ),
    ]
